sonar.projectKey=palcarazm_batchjs-data
sonar.organization=palcarazm
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.coverage.exclusions=**/*.index.ts,**/*.d.ts, scripts/**/*.*js, *.config.*js
sonar.cpd.exclusions=test/**